QUESTIONS_SELF = [
    ("Waktu ada yang muji kamu, kamu merasa…",
     ["Senang dengar kata-katanya",
      "Dihargai karena dia perhatian",
      "Senang kalau dapat hadiah kecil",
      "Diperhatikan karena dia nyempetin waktu",
      "Nyaman kalau dia kasih pelukan atau sentuhan"]),

    ("Kalau seseorang bantu kamu sesuatu tanpa diminta, kamu…",
     ["Senang dengar ucapan baik dari dia",
      "Ngerasa dihargai lewat tindakannya",
      "Suka kalau disertai hadiah kecil",
      "Senang karena dia mau luangin waktu",
      "Ngerasa dekat lewat sentuhan"]),

    ("Pas ulang tahun, kamu lebih suka…",
     ["Ucapan yang tulus",
      "Orang yang bantu ngurus keperluanmu",
      "Hadiah yang bermakna",
      "Waktu bareng tanpa gangguan",
      "Pelukan atau momen fisik"]),

    ("Kalau lagi stres, kamu paling butuh…",
     ["Kata-kata yang nenangin",
      "Bantuan biar urusan beres",
      "Hadiah kecil biar semangat lagi",
      "Diajak ngobrol dengan tenang",
      "Sentuhan atau rangkulan atau pelukan"]),

    ("hangout ideal buat kamu itu…",
     ["Ngobrol yang hangat dan jujur",
      "Orang yang bantu hal-hal kecil",
      "Ada kejutan atau hadiah kecil",
      "Waktu berkualitas berdua",
      "Kedekatan fisik"]),

    ("Kamu merasa aman ketika seseorang…",
     ["Ngomong apa yang dia rasain",
      "Bantu hal-hal sehari-hari",
      "Ngasih tanda kasih kecil lewat hadiah",
      "Luangin waktu buat kamu",
      "Nunjukin kasih sayang lewat sentuhan"]),

    ("Kalau seseorang minta maaf, kamu lebih suka…",
     ["Dengar maaf yang tulus",
      "Lihat dia benerin kesalahannya",
      "Dapat hadiah kecil sebagai tanda damai",
      "Ngobrol baik-baik sampai selesai",
      "Pelukan biar suasana adem"]),

    ("Kamu paling ngerasa disayangi ketika seseorang…",
     ["Ngirim pesan atau catatan manis",
      "Bantu hal-hal praktis",
      "Ngasih kejutan kecil",
      "Fokus ke kamu",
      "Nunjukin kedekatan fisik"]),

    ("Biar merasa dihargai, kamu ingin seseorang…",
     ["Ngasih pujian yang spesifik",
      "Membantu saat kamu butuh",
      "Ngasih sesuatu yang bermakna",
      "Luangin waktu buat berdua",
      "Menunjukkan sentuhan hangat"]),

    ("Hal paling romantis buat kamu itu…",
     ["Kata-kata cinta yang tulus",
      "Tindakan yang menunjukkan perhatian",
      "Hadiah yang thoughtful",
      "Percakapan mendalam",
      "Sentuhan fisik yang lembut"]),

    ("Saat bertengkar, kamu paling cepat tenang kalau…",
     ["Denger kata-kata yang lembut",
      "Masalah diperbaiki",
      "Ada tanda damai kecil",
      "Diajak ngobrol baik-baik",
      "Dikasih pelukan"]),

    ("Kamu suka pujian yang…",
     ["Diucapkan jelas dan jujur",
      "Diiringi tindakan nyata",
      "Kadang disertai hadiah kecil",
      "Diucapkan sambil quality time",
      "Diucapkan sambil ada sentuhan"]),

    ("Kalau seseorang kangen sama kamu, kamu paling ngerasa kalau mereka…",
     ["Ngirim pesan hangat",
      "Bantu hal-hal kecil buat kamu tanpa diminta",
      "Bawa oleh-oleh kecil",
      "Nelpon atau ngobrol lama",
      "Peluk lama pas ketemu"]),

    ("Belajar love language seseorang, kamu lebih suka…",
     ["Denger dia cerita perasaannya",
      "Lihat dari tindakannya",
      "Dapat kejutan kecil",
      "Diperhatiin lewat waktu",
      "Dapat sentuhan hangat"]),
      
    ("Kamu ngerasa diperhatikan kalau seseorang…",
     ["Ngasih kata-kata positif",
      "Bantu nyelesaiin masalah",
      "Ngasih hadiah kecil",
      "Ngabisin waktu bareng",
      "Pegang tanganmu atau peluk"]),

    ("Hari kamu lagi jelek, kamu paling butuh…",
     ["Kata-kata penyemangat",
      "Bantuan nyata tanpa diminta",
      "Hadiah kecil biar mood naik",
      "Teman ngobrol",
      "Sentuhan yang nenangin"]),

    ("Kejutan kecil bikin kamu…",
     ["Senang kalau disertai kata-kata manis.",
      "Ngerasa diperhatiin kalau berguna",
      "Dicintai kalau dipilih dengan maksud",
      "Senang kalau bikin ada waktu bareng",
      "Merasa dekat lewat sentuhan"]),

    ("Merayakan pencapaian, kamu lebih suka…",
     ["Dapet ucapan selamat yang hangat.",
      "Ada yang bantu tugasmu",
      "Dapet hadiah kenangan",
      "Waktu untuk ngerayain bareng",
      "Pelukan hangat"]),

    ("Kalau lagi jauh, kamu merasa dekat kalau seseorang…",
     ["Sering kasih kabar",
      "Lakukan sesuatu biar gampang ketemu",
      "Bawa hadiah kecil pas balik",
      "Rencanain waktu bareng",
      "Peluk erat pas ketemu lagi"]),

    ("Teman bilang kamu menunjukkan cinta lewat…",
     ["Pujian dan kata-kata positif.",
      "Membantu hal-hal kecil",
      "Ngasih hadiah",
      "Luangin waktu buat mereka",
      "Sentuhan ringan pas nyapa"]),

    ("Kenangan yang paling nempel biasanya saat seseorang…",
     ["Ngasih pesan atau surat yang bermakna",
      "Lakuin sesuatu yang perhatian",
      "Ngasih hadiah berkesan",
      "Luangin waktu khusus buat kamu",
      "Momen fisik yang hangat"]),

    ("Kedekatan buat kamu itu…",
     ["Komunikasi yang jujur",
      "Kerja sama dalam hal kecil",
      "Tukar hadiah bermakna",
      "Hadir penuh saat bareng",
      "Sentuhan yang nyaman"]),

    ("Kamu tertarik sama orang yang…",
     ["Bisa nyampein perasaannya dengan kata-kata",
      "Sigap bantuin hal-hal kecil",
      "Perhatian lewat hadiah kecil",
      "Prioritaskan waktu bersama",
      "Hangat dan dekat secara fisik"]),

    ("Dalam hubungan, kamu paling butuh…",
     ["Komunikasi yang jelas",
      "Bantuan nyata",
      "Kejutan atau pemberian kecil",
      "Waktu yang konsisten",
      "Kedekatan fisik"]),

    ("Hal yang ingin kamu perbaiki dari dirimu adalah…",
     ["Lebih sering ngomong hal positif",
      "Lebih sering bantu pasangan",
      "Kadang kasih surprise kecil",
      "Lebih banyak waktu berkualitas",
      "Lebih menunjukkan sentuhan hangat"])
]