QUESTIONS_FRIENDSHIP = [
    ("Saat teman menunjukkan dukungan, kamu paling suka…",
     ["Dia memberi kata-kata semangat",
      "Dia membantu hal-hal kecil",
      "Dia memberi hadiah kecil",
      "Dia menghabiskan waktu bersamamu",
      "Dia memberikan tepukan bahu atau pelukan"]),

    ("Teman yang kamu suka biasanya adalah yang…",
     ["Suka memuji atau menyemangati",
      "Suka membantu tanpa diminta",
      "Suka memberi hadiah kecil",
      "Suka menyediakan waktu untukmu",
      "Suka memberi sentuhan ringan yang hangat"]),

    ("Ketika kamu sedih, teman yang kamu butuhkan adalah yang…",
     ["Bisa menenangkan lewat kata-kata",
      "Mau membantu merapikan masalahmu",
      "Membawakan hadiah kecil untuk menghibur",
      "Ada untuk mendengarkanmu",
      "Memberi pelukan"]),

    ("Kalau temanmu ingin membuat harimu lebih baik, kamu ingin dia…",
     ["Bilang hal-hal positif",
      "Melakukan sesuatu untuk membantu",
      "Memberikan hadiah kecil",
      "Mengajakmu keluar sebentar",
      "Menepuk bahumu dengan hangat"]),

    ("Kamu merasa dihargai teman ketika mereka…",
     ["Memujimu secara spesifik",
      "Membantu tugasmu",
      "Memberi gift kecil",
      "Meluangkan waktu berkualitas",
      "Memberi sentuhan kecil seperti rangkulan"]),

    ("Momen yang paling kamu ingat dari teman biasanya…",
     ["Kata-katanya",
      "Tindakannya",
      "Hadiah darinya",
      "Waktu ngobrol panjang",
      "Sentuhan fisik yang hangat"]),

    ("Hal paling menyentuh dari teman adalah ketika…",
     ["Dia bilang dia peduli",
      "Dia membantu padahal dia sibuk",
      "Dia memberikan sesuatu kecil",
      "Dia menemanimu saat kamu butuh",
      "Dia memeluk atau menepuk bahumu"]),

    ("Saat ulang tahun, kamu paling senang kalau teman…",
     ["Ngucapin kata-kata manis",
      "Bantu menyiapkan acara",
      "Ngasih hadiah kecil",
      "Ngajakmu quality time",
      "Ngasih pelukan hangat"]),

    ("Saat teman lama ketemu kembali, kamu paling terharu kalau dia…",
     ["Bilang dia kangen kamu",
      "Membantu sesuatu buatmu",
      "Bawain oleh-oleh kecil",
      "Nyempetin waktu ngobrol lama",
      "Memberi pelukan"]),

    ("Kamu merasa dekat dengan teman ketika…",
     ["Kalian sering saling cerita",
      "Dia membantu hal-hal kecil",
      "Dia memberi gift kecil",
      "Kalian punya waktu bersama",
      "Dia memberi sentuhan ringan"]),

    ("Kalau temanmu ingin minta maaf, kamu paling suka…",
     ["Dia bilang maaf yang jujur",
      "Dia memperbaiki kesalahan",
      "Dia memberi tanda damai kecil",
      "Dia ajak kamu ngobrol",
      "Dia memberi pelukan ringan"]),

    ("Kamu lebih suka teman yang…",
     ["Jago mengekspresikan pikirannya",
      "Jago membantu hal praktis",
      "Jago memberi hadiah kecil",
      "Jago menyediakan waktu",
      "Jago memberi kehangatan fisik"]),

    ("Teman yang paling kamu inget biasanya adalah yang…",
     ["Perkataannya berkesan",
      "Tindakannya nyata",
      "Hadiah-hadiahnya unik",
      "Waktu yang ia sediakan",
      "Sentuhan fisiknya hangat"]),

    ("Kamu merasa aman dengan teman yang…",
     ["Bicara jujur dan terbuka",
      "Membantu saat kamu butuh",
      "Memberi gift bermakna",
      "Selalu meluangkan waktu",
      "Memberi gesture fisik"]),

    ("Cara teman menunjukkan bahwa dia peduli biasanya lewat…",
     ["Kata-katanya",
      "Tindakannya",
      "Hadiah kecil",
      "Waktu khusus",
      "Sentuhan ringan"]),

    ("Saat kamu capek, dukungan teman yang kamu inginkan adalah…",
     ["Kata-kata penguat",
      "Dia membantu pekerjaanmu",
      "Dia memberimu sesuatu kecil",
      "Dia nemenin kamu istirahat",
      "Dia memelukmu atau menepuk bahu"]),
      
    ("Hal yang bikin kamu nyaman dengan teman adalah…",
     ["Komunikasi yang hangat",
      "Saling bantu",
      "Saling memberi kecil-kecilan",
      "Ngobrol lama bareng",
      "Kedekatan fisik kecil"]),

    ("Kamu tahu temanmu sayang kamu ketika…",
     ["Dia bilang hal-hal tulus",
      "Dia melakukan sesuatu tanpa diminta",
      "Dia memberikan hadiah kecil penuh arti",
      "Dia menyediakan waktu khusus",
      "Dia memberi sentuhan hangat"]),

    ("Saat kalian merayakan sesuatu, kamu paling suka…",
     ["Ucapan manis darinya",
      "Dia yang ngebantu persiapan",
      "Dia ngasih hadiah kecil",
      "Dia habiskan waktu bareng kamu",
      "Dia peluk kamu"]),

    ("Kamu merasa paling didukung teman ketika…",
     ["Dia bilang kamu bisa",
      "Dia bantu biar kamu lebih ringan",
      "Dia beri gift kecil motivasi",
      "Dia luangkan waktu buat kamu",
      "Dia pegang tangan/tepuk bahu"]),

    ("Teman yang kamu butuhkan untuk jangka panjang adalah yang…",
     ["Bisa menguatkan lewat kata-kata",
      "Bisa diandalkan membantu",
      "Bisa memberi hadiah bermakna",
      "Bisa menyediakan waktu rutin",
      "Bisa memberi kenyamanan fisik"]),

    ("Kalau sedang jauh jarak, kamu merasa dekat dengan teman kalau…",
     ["Dia sering chat hal-hal positif",
      "Dia bantu hal-hal jarak jauh",
      "Dia kirim gift kecil",
      "Dia nyempetin telepon",
      "Dia peluk kamu pas ketemu"]),

    ("Kamu merasa tenang dengan teman kalau dia…",
     ["Mengatakan hal-hal lembut",
      "Bantu menyelesaikan masalahmu",
      "Memberikan sesuatu kecil",
      "Melakukan quality time",
      "Memberikan sentuhan konsep fisik"]),

    ("Kamu merasa temanmu perhatian ketika…",
     ["Dia sering bilang hal-hal baik",
      "Dia melakukan sesuatu buatmu",
      "Dia memberi gift kecil",
      "Dia meluangkan waktu buatmu",
      "Dia menunjukkan sentuhan ringan"]),

    ("Tanda pertemanan kuat buat kamu adalah…",
     ["Kata-kata yang saling menguatkan",
      "Saling bantu secara nyata",
      "Saling memberi",
      "Saling luangkan waktu",
      "Saling memberi gesture fisik"]),
]
