QUESTIONS_RELATIONSHIP = [
    ("Saat pasanganmu ingin menunjukkan cinta, kamu paling suka…",
     ["Ucapan manis darinya",
      "Dia membantu hal-hal kecil tanpa diminta",
      "Dia memberi hadiah kecil yang bermakna",
      "Dia meluangkan waktu khusus untukmu",
      "Dia memeluk atau menggenggam tanganmu"]),

    ("Saat kamu bertengkar dengan pasangan, kamu paling cepat tenang kalau…",
     ["Dia mengatakan kata-kata lembut",
      "Dia memperbaiki masalah dengan tindakan nyata",
      "Dia memberi hadiah kecil sebagai permintaan maaf",
      "Dia mengajakmu ngobrol dengan tenang",
      "Dia memelukmu dengan hangat"]),

    ("Momen paling berkesan dengan pasangan buat kamu biasanya saat…",
     ["Dia mengatakan hal-hal tulus",
      "Dia membantu tanpa harus ditanya",
      "Dia memberi kejutan kecil",
      "Kalian menghabiskan waktu berdua",
      "Ada sentuhan fisik yang hangat"]),

    ("Saat pasanganmu ingin membuatmu bahagia, kamu lebih suka…",
     ["Dia memujimu",
      "Dia melakukan sesuatu untukmu",
      "Dia memberikan hadiah thoughtful",
      "Dia menyediakan waktu tanpa distraksi",
      "Dia menunjukkan kasih sayang lewat sentuhan"]),

    ("Hal paling romantis menurutmu adalah…",
     ["Kata-kata cinta yang tulus",
      "Tindakan kecil penuh perhatian",
      "Hadiah yang penuh makna",
      "Quality time yang intim",
      "Sentuhan lembut seperti pelukan"]),

    ("Kamu merasa dihargai pasangan ketika…",
     ["Dia mengucapkan hal-hal positif",
      "Dia membantu mengurus sesuatu",
      "Dia memberi sesuatu untukmu",
      "Dia hadir sepenuhnya untukmu",
      "Dia meraih tanganmu atau memelukmu"]),

    ("Kalau kamu sedang sedih, kamu butuh pasangan…",
     ["Mengatakan kata-kata yang menenangkan",
      "Membantu merapikan atau mengurus keperluanmu",
      "Membawakan hadiah kecil untuk menghiburmu",
      "Mengajakmu bicara lama",
      "Memelukmu erat"]),

    ("Cara pasanganmu meminta maaf yang paling kamu hargai adalah…",
     ["Ucapan maaf yang jujur",
      "Dia langsung memperbaiki situasi",
      "Dia memberi tanda damai kecil",
      "Dia duduk bersamamu untuk membicarakannya",
      "Dia memelukmu sambil menenangkan"]),

    ("Ketika pasanganmu pulang setelah lama pergi, kamu paling suka…",
     ["Dia mengatakan dia merindukanmu",
      "Dia membantu membereskan hal-hal yang kamu kerjakan",
      "Dia membawakan oleh-oleh kecil",
      "Dia meluangkan waktu khusus untukmu",
      "Dia memelukmu lama"]),

    ("Kamu merasa dekat dengan pasangan ketika dia…",
     ["Mengungkapkan perasaannya dengan kata-kata",
      "Mengerjakan sesuatu untukmu",
      "Memberi hadiah yang menunjukkan perhatian",
      "Menghabiskan waktu berkualitas bersama",
      "Menunjukkan sentuhan fisik"]),

    ("Hal yang kamu syukuri dari pasangan biasanya saat dia…",
     ["Mengatakan hal-hal yang membuatmu merasa dihargai",
      "Membantu tugas-tugasmu",
      "Memberimu kejutan kecil",
      "Mengajakmu quality time",
      "Memberimu sentuhan kasih sayang"]),

    ("Kamu merasa dicintai pasangan saat…",
     ["Dia sering memberi pujian",
      "Dia berinisiatif melakukan hal buatmu",
      "Dia mengingatkanmu lewat hadiah kecil",
      "Dia fokus padamu ketika ngobrol",
      "Dia memeluk atau menyentuhmu dengan lembut"]),

    ("Cara pasanganmu menunjukkan dukungan paling terasa buatmu adalah…",
     ["Kata-kata penyemangat",
      "Bantuan nyata",
      "Hadiah kecil yang meaningful",
      "Waktu mendengarkan cerita kamu",
      "Sentuhan menenangkan"]),

    ("Saat ulang tahunmu, kamu paling suka pasangan…",
     ["Mengucapkan kata-kata manis",
      "Membantumu menyiapkan hal-hal penting",
      "Memberimu hadiah penuh arti",
      "Menghabiskan hari bersama",
      "Memberimu pelukan hangat"]),

    ("Ketika pasanganmu sibuk, hal yang paling kamu rindukan adalah…",
     ["Pesan-pesan manisnya",
      "Dia membantu hal sederhana untukmu",
      "Dia memberi gift kecil tanda perhatian",
      "Dia menyisihkan waktu untukmu",
      "Sentuhan fisik ketika bertemu"]),

    ("Kamu merasa hubunganmu kuat ketika pasangan…",
     ["Sering berkomunikasi denganmu",
      "Mengerjakan sesuatu demi kebaikanmu",
      "Memberi hadiah bermakna",
      "Menghabiskan waktu rutin bersama",
      "Memberikan sentuhan afeksi"]),

    ("Kamu paling tersentuh ketika pasangan…",
     ["Mengatakan bahwa dia bangga padamu",
      "Melakukan hal yang meringankan bebanmu",
      "Memberimu sesuatu tanpa alasan",
      "Mengajakmu deep talk",
      "Memelukmu tiba-tiba"]),

    ("Saat pasangan menunjukkan cinta, kamu lebih menghargai…",
     ["Kata-kata romantis",
      "Tindakan nyata",
      "Hadiah thoughtful",
      "Waktu berkualitas",
      "Sentuhan fisik"]),   
]